plugins {
    id 'com.android.application'
}

android {
    namespace 'com.flogdoog.app'
    compileSdk 34

    defaultConfig {
        applicationId 'com.flogdoog.app'
        minSdk 24
        targetSdk 34
        versionCode 4
        versionName '1.3'
    }

    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'flogdoog2026'
            keyAlias 'flogdoog'
            keyPassword 'flogdoog2026'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
        debug {
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    // FileProvider（应用内更新用）
    implementation 'androidx.core:core:1.13.1'
}
